name: pull-request
on: 
  pull_request:
    branches:
      - main
jobs:
  build-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: build cats-game
        run: |
            cd ./cat-game
            npm install
            npm run build