name: pull-request
on: 
  pull_request:
    branches:
      - main
jobs:
  build-cats-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd ./cat-game
      - run: npm install
      - run: npm run build